
build: HockeyDBInterface.class

HockeyDBInterface.class: HockeyDBInterface.java
	javac HockeyDBInterface.java

run: HockeyDBInterface.class
	java -cp .:postgresql-42.7.5.jar HockeyDBInterface

clean:
	rm HockeyDBInterface.class
	rm HockeyDB.class
	rm TablePrinter.class
	rm Populator.class
